### ISSUE TITLE
R Execution halted

### ISSUE THREAD

**Issue by SC-Duan** [Sanrrone/GGisy#1]
Hi,
I get an error when using this script, can you give me some help?

Error in unfactor(linkr[i, 4]) :
  Please provide the obj which can be a matrix, data.frame or a vector. The provided obj has the class of integer
Execution halted

Here is a part of the synteny.tsv:
HiC_scaffold_1  5       99.925  51125733        51437065        22751070        22439578
HiC_scaffold_1  5       99.860  29951110        30199612        42399353        42150656
HiC_scaffold_1  5       99.805  16105579        16312433        62040082        62247087
HiC_scaffold_1  5       99.806  41660509        41865535        30778119        30572819
HiC_scaffold_1  5       99.846  51453783        51645912        22422894        22230588
HiC_scaffold_1  5       99.955  38400555        38561758        34199267        34038001
HiC_scaffold_1  5       99.794  33528214        33686880        38934820        38775941
HiC_scaffold_1  5       99.573  35843804        35995518        36685945        36533947
HiC_scaffold_1  5       99.885  50434271        50583965        23490970        23341122
HiC_scaffold_1  5       99.930  50962367        51110045        22914362        22766592
HiC_scaffold_1  5       99.699  48181681        48329826        24615693        24467403
HiC_scaffold_1  5       99.923  29425001        29566246        42927128        42785792
HiC_scaffold_1  5       99.935  38226711        38365504        34373258        34234379
HiC_scaffold_1  5       99.617  20596919        20734848        66514483        66652601
HiC_scaffold_1  5       99.886  17508557        17641777        63341948        63475201
HiC_scaffold_1  5       99.842  28843493        28976594        43635388        43502145
HiC_scaffold_1  5       99.911  53415737        53546098        20447355        20316926
HiC_scaffold_1  5       99.906  15981416        16105517        61916015        62040119
HiC_scaffold_1  5       99.705  14290279        14414631        59348510        59473075
HiC_scaffold_1  5       99.747  38561893        38682586        34038029        33917252
HiC_scaffold_1  5       99.647  68954903        69072634        7896204 7778253
HiC_scaffold_1  5       99.942  28691846        28804435        43787103        43674456
......

Thank you!

**Comment by Sanrrone** [comment]
Hi,
thanks for reporting the bug, but I would need more information to solve it, could you give the following things, just to reproduce your error:
* line code you use
* the two genomes you use.

It seems an error with the headers name in the reference genome, check the scaffolds names and remove the spaces or replace it with "_".

hope it can help.
cheers

**Comment by SC-Duan** [comment]
Hi,
This is my code:
python ~/GGisy/GGisy.py -r GRCz11.dna.chr.fa -q Reduced.FINAL.chr.fasta
-i 70 -e 1e-5 -t 20 -c False
The IDs in GRCz11.dna.chr.fa are,
>1
>2
>3
>4
>5
>6
>7
>8
>9
>10
>11
>12
>13
>14
>15
>16
>17
>18
>19
>20
>21
>22
>23
>24
>25
and the IDs in Reduced.FINAL.chr.fasta are,
>HiC_scaffold_1
>HiC_scaffold_2
>HiC_scaffold_3
>HiC_scaffold_4
>HiC_scaffold_5
>HiC_scaffold_6
>HiC_scaffold_7
>HiC_scaffold_8
>HiC_scaffold_9
>HiC_scaffold_10
>HiC_scaffold_11
>HiC_scaffold_12
>HiC_scaffold_13
>HiC_scaffold_14
>HiC_scaffold_15
>HiC_scaffold_16
>HiC_scaffold_17
>HiC_scaffold_18
>HiC_scaffold_19
>HiC_scaffold_20
>HiC_scaffold_21
>HiC_scaffold_22
>HiC_scaffold_23
>HiC_scaffold_24
>HiC_scaffold_25
Sorry I can not upload the genome files, but the sequences should be correct.
Thank you!

**Comment by Sanrrone** [comment]
Hi, that was helpful, I already fixed the code, try to download again and tell me if works.

cheers

**Comment by Sanrrone** [comment]
closed by non feedback. Assuming the fix worked
