### ISSUE TITLE
GGisy problem

### ISSUE THREAD

**Issue by LennWhy** [Sanrrone/GGisy#3]
Hi,

I am trying to align two genomes (a denovo and a reference from a closely-related species), but I run GGisy I get the following error:

`Traceback (most recent call last):
  File "../GGisy-master/GGisy.py", line 385, in <module>
    filterBlastOutput(blastout=blastout, alignL=mainV.v3, evalue=mainV.v4, identity=mainV.v5, coverage=mainV.v9, outfile=mainV.v10)
  File "../GGisy-master/GGisy.py", line 125, in filterBlastOutput
    cov = (toint/float(line[12]))*100`

I think it might have to do with the TSV file generated but I am unsure. Can you please advise?

Thanks much!

**Comment by Sanrrone** [comment]
Hi!, could you attach the input files? or a sample of them, just to reproduce the error and do the tracking. It seems there are no hits between the genomes.

**Comment by LennWhy** [comment]
Hi, thanks for the help! 

I can't seem to be able able to attach any files on here somehow. Do you have an alternative method? I can send you a sample of the scaffold, the ref genome and the tsv file generated from using -b parameter.

L

**Comment by Sanrrone** [comment]
I think the method to upload small files is putting them all in a compressed file (.zip). otherwise you can just write it here using the triple `.

**Comment by LennWhy** [comment]
[Archive.zip](https://github.com/Sanrrone/GGisy/files/13500667/Archive.zip)

Thanks! Attached are the tsv file and a sample sequence. The reference genome is too large to be attached, but I can provide the [NCBI link](https://www.ncbi.nlm.nih.gov/datasets/taxonomy/173247/).  It's the genome of the suckerfish, E. naucrates.

**Comment by Sanrrone** [comment]
I ran the cloned version of the repo and with the genome you provide and there is no match between the sequences, also I tried with the tsv you provide but it has a different format. could you try to make the tsv using this format?:
```
-outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qlen
```

**Comment by LennWhy** [comment]
I ran the following command to obtain the tsv file (after running GGisy not working) for the -b parameter:

`blastn -query scaffold2.fa -db ../E.naucrates_genome/GCA_031770045.1/Ena_ref -outfmt 6 -evalue 80 -strand both -num_threads 8 -out scaffold2.tsv` And so the format should be correct, i.e., -outfmt 6. I am not sure why it would match.

Also, I should have specified the genome version, which is GCA_031770045.1. Did you use that version?

**Comment by Sanrrone** [comment]
I used a modified format 6 that's why I specified the columns.
and the same genome you used in your search must be the one you use to run the script

**Comment by LennWhy** [comment]
I see. I've modified the `-outfmt` to include `qlen`, but I now get the following error:

```
Attaching package: ‘varhandle’

The following object is masked from ‘package:S4Vectors’:

    unfactor

Error in read.table(handlefile, sep = "\t", stringsAsFactors = F, check.names = F) : 
  no lines available in input
Execution halted
```

**Comment by Sanrrone** [comment]
that's strange, its continue saying there is no match between the sequences, at least at 50% identity and 50% coverage. I'll look what is happening with the R code

**Comment by LennWhy** [comment]
Just in case, attached is the updated .tsv file, which I used with -b. Also, the genome that I am using is [GCA_031770045.1_ASM3177004v1_genomic.fna](https://www.ncbi.nlm.nih.gov/datasets/genome/GCA_031770045.1/)
[scaffold2_1.tsv.zip](https://github.com/Sanrrone/GGisy/files/13502488/scaffold2_1.tsv.zip)

**Comment by Sanrrone** [comment]
Hi,
I used the files you provided, and at it was expected is because the blast matching are too low for the parameters (50 identity and 50 coverage for the whole query). To include everything you have to set the parameters `-i 0 -c 0`.
I updated the code to have better tracking in case of more errors.

thanks for your help!
 
[synteny.pdf](https://github.com/Sanrrone/GGisy/files/13523492/synteny.pdf)

**Comment by LennWhy** [comment]
Beautiful! I tested the new code, and it works. Thank you so much for your help and time!!!!!
